; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = DCO4 Voice Board
src_dir = /home/felipe/Documentos/DCO4-REBORN/DCO/
default_envs = rpipico2

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board_build.usb_stack = tinyusb
board_build.arduino.earlephilhower.usb_manufacturer = DCO4
board_build.arduino.earlephilhower.usb_product = DCO4-REBORN
build_unflags = -Os
build_flags = 
	-DPICO_COPY_TO_RAM=1
	-DCMAKE_BUILD_TYPE=Release
	-O3
	-DUSE_TINYUSB
	
lib_ldf_mode = deep+
lib_archive = no
lib_ignore = MO-LFO
lib_extra_dirs = ${platformio.src_dir}/_build_libs
monitor_speed = 2000000
custom_usb_by_id = /dev/serial/by-id/usb-*DCO4?REBORN*
monitor_port = /dev/serial/by-id/usb-*DCO4?REBORN*
upload_port = /dev/serial/by-id/usb-*DCO4?REBORN*
upload_protocol = picotool
extra_scripts = post:no_verify_upload.py
build_src_filter = 
	+<*>
	-<_build_libs/>
	-<docs/>
	-<tools/>

[env:rpipico2]
board = rpipico2
board_build.filesystem_size = 0.5m
board_build.f_cpu = 250000000L

[env:dco_pico]
board = pico
board_build.f_cpu = 225000000L
